# syntax=docker/dockerfile:1

FROM golang:1.22

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download


ADD . .
# make sure we have a .env

RUN touch .env



# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /drainer src/hatchet-load-test/drainer/main.go

# Run
CMD ["/drainer"]