# syntax=docker/dockerfile:1

FROM golang:1.22

# Set destination for COPY
WORKDIR /app

# Download Go modules
COPY go.mod go.sum ./
RUN go mod download


ADD . .
# make sure we have a .env

RUN touch .env

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /emitter src/hatchet-load-test/emitter/main.go
RUN CGO_ENABLED=0 GOOS=linux go build -o /loadtest examples/loadtest/cli 

# Run
CMD ["/emitter"]